// Datos de prueba usados por src/lib/data/ordenes.ts mientras Supabase no está
// configurado (o mientras Persona A todavía no comparte el proyecto real).
// Tienen la MISMA forma que las filas reales (ver database.types.ts) para que
// el swap a Supabase en Día 3 no rompa nada en la UI.

import type { Cliente, Profesional, OrdenServicio } from "@/types";

export const mockClientes: Cliente[] = [
  {
    id: 1,
    nombre_cliente: "Bolívar Seguros S.A.",
    nit: "860.002.964-1",
    activo: true,
    fecha_creacion: "2026-01-10T08:00:00Z",
  },
  {
    id: 2,
    nombre_cliente: "Constructora Andina Ltda.",
    nit: "900.123.456-7",
    activo: true,
    fecha_creacion: "2026-01-15T08:00:00Z",
  },
  {
    id: 3,
    nombre_cliente: "Textiles del Norte S.A.S.",
    nit: "800.987.654-3",
    activo: true,
    fecha_creacion: "2026-02-01T08:00:00Z",
  },
];

export const mockProfesionales: Profesional[] = [
  {
    id: 1,
    nombre_completo: "Laura Sofía Gil Chaves",
    cedula: "1010123456",
    email: "laura.gil@example.com",
    telefono: "3001234567",
    activo: true,
    fecha_creacion: "2026-01-05T08:00:00Z",
    valor_hora: 45000,
  },
  {
    id: 2,
    nombre_completo: "Mauricio Monroy",
    cedula: "1020987654",
    email: "mauricio.monroy@example.com",
    telefono: "3009876543",
    activo: true,
    fecha_creacion: "2026-01-05T08:00:00Z",
    valor_hora: 45000,
  },
  {
    id: 3,
    nombre_completo: "Camila Restrepo Vélez",
    cedula: "1030456789",
    email: "camila.restrepo@example.com",
    telefono: "3012345678",
    activo: true,
    fecha_creacion: "2026-01-06T08:00:00Z",
    valor_hora: null,
  },
];

export const mockOrdenes: OrdenServicio[] = [
  {
    id: 1,
    cliente_id: 1,
    id_unico: "OS-2026-0001",
    estado: "Programar urgente",
    numero_os_cliente: "B-4521",
    fecha_recepcion_os: "2026-06-15",
    empresa_usuaria_id: 1,
    nombre_empresa_usuaria: "Bolívar Seguros S.A.",
    nit_empresa_usuaria: "860.002.964-1",
    cronograma: 1,
    secuencia: "1/1",
    nombre_servicio: "Examen médico ocupacional de ingreso",
    horas_cargadas: 2,
    tipo_servicio: "Asesoría",
    fecha_sipab: "2026-06-16",
    asesor_gestion_riesgos: "Laura Sofía Gil Chaves",
    observaciones_iniciales: "Urgente, cliente pidió prioridad.",
    tarifa_valor_transporte: "25000",
    responsable_sec_id: 1,
    responsable_os: "Bibiana Sarmiento",
    observaciones_responsable_sec: "Se confirmó agenda con la empresa usuaria.",
    link_archivo_orden: "https://drive.google.com/file/d/mock-os-0001",
    fecha_creacion: "2026-06-15T09:00:00Z",
    fecha_actualizacion: "2026-06-15T09:00:00Z",
  },
  {
    id: 2,
    cliente_id: 2,
    id_unico: "OS-2026-0002",
    estado: "Facturada",
    numero_os_cliente: "CA-990",
    fecha_recepcion_os: "2026-05-20",
    empresa_usuaria_id: 2,
    nombre_empresa_usuaria: "Constructora Andina Ltda.",
    nit_empresa_usuaria: "900.123.456-7",
    cronograma: 2,
    secuencia: "1/1",
    nombre_servicio: "Evaluación de riesgo psicosocial",
    horas_cargadas: 4,
    tipo_servicio: "Informe técnico",
    fecha_sipab: "2026-05-22",
    asesor_gestion_riesgos: "Mauricio Monroy",
    observaciones_iniciales: null,
    tarifa_valor_transporte: "40000",
    responsable_sec_id: 2,
    responsable_os: "Daniela Rosso",
    observaciones_responsable_sec: null,
    link_archivo_orden: null,
    fecha_creacion: "2026-05-20T09:00:00Z",
    fecha_actualizacion: "2026-06-02T09:00:00Z",
  },
  {
    id: 3,
    cliente_id: 3,
    id_unico: "OS-2026-0003",
    estado: "Pendiente revisión Bolívar",
    numero_os_cliente: "TN-112",
    fecha_recepcion_os: "2026-06-28",
    empresa_usuaria_id: 3,
    nombre_empresa_usuaria: "Textiles del Norte S.A.S.",
    nit_empresa_usuaria: "800.987.654-3",
    cronograma: null,
    secuencia: null,
    nombre_servicio: "Capacitación en manejo de cargas",
    horas_cargadas: 6,
    tipo_servicio: "Capacitación",
    fecha_sipab: null,
    asesor_gestion_riesgos: "Laura Sofía Gil Chaves",
    observaciones_iniciales: "Pendiente confirmar sede.",
    tarifa_valor_transporte: null,
    responsable_sec_id: 1,
    responsable_os: "Bibiana Sarmiento",
    observaciones_responsable_sec: "Falta dirección exacta de la sede.",
    link_archivo_orden: null,
    fecha_creacion: "2026-06-28T09:00:00Z",
    fecha_actualizacion: "2026-06-28T09:00:00Z",
  },
  {
    id: 4,
    cliente_id: 1,
    id_unico: "OS-2026-0004",
    estado: "Programar mes siguiente",
    numero_os_cliente: "B-4530",
    fecha_recepcion_os: "2026-06-20",
    empresa_usuaria_id: 1,
    nombre_empresa_usuaria: "Bolívar Seguros S.A.",
    nit_empresa_usuaria: "860.002.964-1",
    cronograma: 1,
    secuencia: "1/2",
    nombre_servicio: "Visita de inspección de riesgos locativos",
    horas_cargadas: 3,
    tipo_servicio: "N/A",
    fecha_sipab: "2026-06-21",
    asesor_gestion_riesgos: "Camila Restrepo Vélez",
    observaciones_iniciales: null,
    tarifa_valor_transporte: "30000",
    responsable_sec_id: 3,
    responsable_os: "Lucia Bejarano",
    observaciones_responsable_sec: null,
    link_archivo_orden: "https://drive.google.com/file/d/mock-os-0004",
    fecha_creacion: "2026-06-20T09:00:00Z",
    fecha_actualizacion: "2026-06-25T09:00:00Z",
  },
];
